import { WorkPackageItem, GapItem, DecisionItem, EvidenceItem } from './types.ts';

export const WORK_PACKAGES: WorkPackageItem[] = [
  {
    id: 'WP-01',
    title: 'Canonical Discovery & Repository Bootstrap',
    phase: 'Phase 0 — Discovery',
    dependencies: 'None',
    riskClass: 'R0',
    status: 'ACCEPTED_COMPLETE',
    exitEvidence: 'Manifest, contracts, project control, public discovery engine, 11/11 tests green',
  },
  {
    id: 'WP-02',
    title: 'Provenance Store + Connector Registry + Cursors',
    phase: 'Phase 1 — Foundation',
    dependencies: 'WP-01',
    riskClass: 'R0',
    status: 'READY',
    exitEvidence: 'Deterministic ingest contract tests; append-only raw observation proof',
  },
  {
    id: 'WP-03',
    title: 'LARI Site Graph Discovery Adapter',
    phase: 'Phase 0 — Discovery',
    dependencies: 'WP-01, WP-02',
    riskClass: 'R0',
    status: 'PENDING',
    exitEvidence: 'Known URL universe reconciliation from router/sitemap/crawl inputs',
  },
  {
    id: 'WP-04',
    title: 'Metric Registry + Canonical Funnel/Event Contract',
    phase: 'Phase 1 — Foundation',
    dependencies: 'WP-01',
    riskClass: 'R0',
    status: 'PENDING',
    exitEvidence: 'Versioned event/metric schemas and data-minimization tests',
  },
  {
    id: 'WP-05',
    title: 'Search Console Read Connector',
    phase: 'Phase 1 — Foundation',
    dependencies: 'WP-02, WP-03',
    riskClass: 'R0',
    status: 'PENDING',
    exitEvidence: 'Search Analytics + URL Inspection ingestion with quota/completeness metadata',
  },
  {
    id: 'WP-06',
    title: 'GA4 Read Connector',
    phase: 'Phase 1 — Foundation',
    dependencies: 'WP-02, WP-04',
    riskClass: 'R0',
    status: 'PENDING',
    exitEvidence: 'Quota-aware incremental reports, canonical metric mapping, freshness proof',
  },
  {
    id: 'WP-07',
    title: 'CRM / Booking / Revenue Read Model',
    phase: 'Phase 1 — Foundation',
    dependencies: 'WP-02, WP-04',
    riskClass: 'R0',
    status: 'PENDING',
    exitEvidence: 'Lead -> consultation -> booking -> realized value join contract',
  },
  {
    id: 'WP-08',
    title: 'Deterministic Technical SEO Detector Engine',
    phase: 'Phase 2 — Technical SEO',
    dependencies: 'WP-03, WP-05',
    riskClass: 'R0',
    status: 'PENDING',
    exitEvidence: 'Fixture-backed detection of canonical/sitemap/link/hreflang/schema defects',
  },
  {
    id: 'WP-09',
    title: 'Experiment Ledger + Opportunity Queue + Scoring v0',
    phase: 'Phase 2 — Technical SEO',
    dependencies: 'WP-04..WP-08',
    riskClass: 'R0',
    status: 'PENDING',
    exitEvidence: 'Evidence-linked hypotheses; no unproven claims; pre-registration records',
  },
  {
    id: 'WP-10',
    title: 'AOS Execution Adapter in SHADOW Mode',
    phase: 'Phase 5 — Closed Loop',
    dependencies: 'WP-01, WP-09, Live AOS',
    riskClass: 'R0',
    status: 'PENDING',
    exitEvidence: 'GrowthWorkIntent -> AOS receipt contract proven with zero mutation',
  },
];

export const OPEN_GAPS: GapItem[] = [
  {
    id: 'GAP-001',
    description: 'Exact current LARI route/build manifest and deployed URL set',
    whyItMatters: 'Defines real canonical page universe for G1 exit gate',
    status: 'OPEN',
    blockingPhase: 'WP-03, G1',
    targetResolution: 'Ingest from public crawl / route registry fixture / LARI repo export',
  },
  {
    id: 'GAP-002',
    description: 'Current locales, markets, services, clinics/providers actually represented',
    whyItMatters: 'Required for entity mapping, taxonomy graph, and market segmentation',
    status: 'OPEN',
    blockingPhase: 'WP-03, Phase 3',
    targetResolution: 'Extract from public multilingual page tree & service hierarchy',
  },
  {
    id: 'GAP-003',
    description: 'Google Search Console property IDs and API service account credentials',
    whyItMatters: 'Required for real Search Analytics & URL Inspection ingestion',
    status: 'OPEN',
    blockingPhase: 'WP-05',
    targetResolution: 'Await authorized read-only credentials via secure config',
  },
  {
    id: 'GAP-004',
    description: 'Google Analytics 4 property ID, data stream config, and custom events',
    whyItMatters: 'Needed for real session, funnel, and attribution tracking',
    status: 'OPEN',
    blockingPhase: 'WP-06, G2',
    targetResolution: 'Await authorized read-only GA4 service account / client ID',
  },
  {
    id: 'GAP-005',
    description: 'CRM lead and stage schema',
    whyItMatters: 'Required for joining acquisition traffic with lead qualification status',
    status: 'OPEN',
    blockingPhase: 'WP-07, G3',
    targetResolution: 'Await CRM export or read connector specification',
  },
  {
    id: 'GAP-006',
    description: 'Booking / consultation / revenue / refund schema',
    whyItMatters: 'Required to calibrate multi-objective commercial optimization function',
    status: 'OPEN',
    blockingPhase: 'WP-07, Phase 4',
    targetResolution: 'Await commercial transaction data model and definitions',
  },
  {
    id: 'GAP-007',
    description: 'Google Business Profile listing inventory and API access',
    whyItMatters: 'Local entity consistency, reputation monitoring, and discovery',
    status: 'OPEN',
    blockingPhase: 'Later presence connector',
    targetResolution: 'Await approved GBP project credentials',
  },
  {
    id: 'GAP-008',
    description: 'Bing Webmaster REST property and OAuth2 access',
    whyItMatters: 'Cross-engine visibility monitoring',
    status: 'OPEN',
    blockingPhase: 'Later connector',
    targetResolution: 'Await Bing Webmaster API credentials',
  },
  {
    id: 'GAP-009',
    description: 'Formal consent and privacy classification policy',
    whyItMatters: 'Health-tourism privacy compliance and data minimization boundary',
    status: 'OPEN',
    blockingPhase: 'G0, G2',
    targetResolution: 'Review legal guidelines on patient consultation data handling',
  },
  {
    id: 'GAP-010',
    description: 'Current LARI deployment/canary/rollback mechanics',
    whyItMatters: 'Required for executable change design in non-prod',
    status: 'OPEN',
    blockingPhase: 'G7, G8',
    targetResolution: 'Ingest LARI deployment pipeline documentation',
  },
  {
    id: 'GAP-011',
    description: 'Canonical AOS callable execution interface and authority contract',
    whyItMatters: 'Binds the abstract AosExecutionPort (D-009) to live execution runtime',
    status: 'OPEN',
    blockingPhase: 'WP-10, G5',
    targetResolution: 'Fresh-read live AOS API/CLI specification when available',
  },
  {
    id: 'GAP-012',
    description: 'Current AOS evidence taxonomy mapping',
    whyItMatters: 'Prevents conflicting evidence semantics between Growth OS and AOS',
    status: 'OPEN',
    blockingPhase: 'WP-10',
    targetResolution: 'Align evidence ID namespaces with AOS evidence store',
  },
];

export const CANONICAL_DECISIONS: DecisionItem[] = [
  {
    id: 'D-001',
    title: 'Separate Growth OS Repository Boundary',
    status: 'ACCEPTED',
    decision: 'Isolate Growth OS in dedicated repository (MertSGI/lari-growth-os) rather than nesting in AOS or LARI.',
    rationale: 'Preserves AOS as a generic autonomous engine; prevents mixing commercial logic with product code.',
    evidenceLevel: 'E1',
    riskClass: 'R0',
  },
  {
    id: 'D-002',
    title: 'Collapse Roles into 6 Logical Capability Lanes',
    status: 'ACCEPTED',
    decision: 'Structure domain intelligence into 6 capability lanes with deterministic-first rules.',
    rationale: 'Avoids agent proliferation and saves LLM compute on mechanical checks.',
    evidenceLevel: 'E1',
    riskClass: 'R0',
  },
  {
    id: 'D-003',
    title: 'Append-Only Observation Store & Versioned State',
    status: 'ACCEPTED',
    decision: 'All source data stored with immutable checksums and provenance; derivations versioned.',
    rationale: 'Auditability and deterministic reproducibility for all analytical claims.',
    evidenceLevel: 'E1',
    riskClass: 'R0',
  },
  {
    id: 'D-004',
    title: 'Domain-Owned Read Adapters, AOS-Owned Mutations',
    status: 'ACCEPTED',
    decision: 'Growth OS reads directly; mutations must be requested via AOS work intents.',
    rationale: 'Enforces governance red lines while allowing domain-specific data extraction.',
    evidenceLevel: 'E1',
    riskClass: 'R0',
  },
  {
    id: 'D-005',
    title: 'Vendor-Neutral Canonical Event Envelope',
    status: 'ACCEPTED',
    decision: 'Growth OS maintains its own internal event model; GA4 is a projection, not truth source.',
    rationale: 'Ensures schema ownership, auditability, and protection against vendor changes.',
    evidenceLevel: 'E1',
    riskClass: 'R0',
  },
  {
    id: 'D-006',
    title: 'Multi-Dimensional Risk Matrix (R0-R3)',
    status: 'ACCEPTED',
    decision: 'Compute risk across 8 dimensions; clinical/legal/pricing strictly triggers R3 HUMAN_REQUIRED.',
    rationale: 'Guarantees compliance in sensitive health-tourism context; production remains NO_GO.',
    evidenceLevel: 'E1',
    riskClass: 'R0',
  },
  {
    id: 'D-007',
    title: 'Durable Experiment Ledger',
    status: 'ACCEPTED',
    decision: 'Every material change pre-registered in ledger with honest causal assignment labeling.',
    rationale: 'Prevents misleading statistical claims in organic search settings.',
    evidenceLevel: 'E1',
    riskClass: 'R0',
  },
  {
    id: 'D-008',
    title: 'Isolated Domain Data Plane & Deterministic Cost Rules',
    status: 'ACCEPTED',
    decision: 'Growth data kept separated from customer health data; cheap deterministic checks run before LLMs.',
    rationale: 'Strict compliance with patient privacy and cloud cost guardrails.',
    evidenceLevel: 'E1',
    riskClass: 'R0',
  },
  {
    id: 'D-009',
    title: 'AOS Work-Intent Port / Receipt Decoupling',
    status: 'ACCEPTED',
    decision: 'Growth OS outputs GrowthWorkIntent and receives AosExecutionReceipt.',
    rationale: 'Transports (CLI, HTTP, gRPC) can evolve without touching domain policies.',
    evidenceLevel: 'E1',
    riskClass: 'R0',
  },
  {
    id: 'D-010',
    title: 'GSC Search Analytics Treated as Partial by Contract',
    status: 'ACCEPTED',
    decision: 'Never treat Search Console row queries as 100% exhaustive demand truth.',
    rationale: 'Official API documentation defines truncation and anonymization limits.',
    evidenceLevel: 'E1',
    riskClass: 'R0',
  },
  {
    id: 'D-011',
    title: 'Bing REST/OAuth2 Mandate',
    status: 'ACCEPTED',
    decision: 'Prohibit deprecated SOAP/POX endpoints retired on 2026-08-31; require modern REST.',
    rationale: 'API deprecation compliance.',
    evidenceLevel: 'E1',
    riskClass: 'R0',
  },
  {
    id: 'D-012',
    title: 'No Hard-Coded Objective Weights Pre-Baseline',
    status: 'ACCEPTED',
    decision: 'Calibrate multi-objective optimization function against real historical data.',
    rationale: 'Prevents optimization for vanity traffic over genuine qualified patient bookings.',
    evidenceLevel: 'E1',
    riskClass: 'R0',
  },
  {
    id: 'D-013',
    title: 'TypeScript & JSON Schema Verification Invariants',
    status: 'ACCEPTED',
    decision: 'Enforce all project manifests and interfaces via automated test runner.',
    rationale: 'Guarantees that no developer or agent can silently breach constraints.',
    evidenceLevel: 'E2',
    riskClass: 'R0',
  },
];

export const EVIDENCE_RECORDS: EvidenceItem[] = [
  {
    id: 'EVD-001',
    wpId: 'WP-01',
    claim: 'Explicit repository identity (MertSGI/lari-growth-os) in project manifest',
    level: 'E1',
    sourceType: 'File',
    result: 'PASS',
    actualResult: 'Valid project_manifest.json with explicit keys verified',
  },
  {
    id: 'EVD-002',
    wpId: 'WP-01',
    claim: 'Canonical handoff revision 1.2 materialized in docs/project-control/',
    level: 'E1',
    sourceType: 'File',
    result: 'PASS',
    actualResult: 'Full 29 sections present in docs/project-control/CANONICAL_HANDOFF.md',
  },
  {
    id: 'EVD-003',
    wpId: 'WP-01',
    claim: 'Production NO_GO constraint documented in machine-readable manifest & STATE.md',
    level: 'E1',
    sourceType: 'File',
    result: 'PASS',
    actualResult: 'Manifest production_authority="NO_GO" and deployment authority disabled',
  },
  {
    id: 'EVD-004',
    wpId: 'WP-01',
    claim: 'All 12 canonical open evidence gaps cataloged in OPEN_GAPS.md',
    level: 'E1',
    sourceType: 'File',
    result: 'PASS',
    actualResult: 'GAP-001 through GAP-012 documented with blocking phases and resolution paths',
  },
  {
    id: 'EVD-005',
    wpId: 'WP-01',
    claim: 'Project control files exist and pass automated consistency check',
    level: 'E2',
    sourceType: 'AutomatedTest',
    result: 'PASS',
    actualResult: '6/6 bootstrap assertions passed in tests/bootstrap_invariants.test.ts',
  },
  {
    id: 'EVD-006',
    wpId: 'WP-01',
    claim: 'Public LARI discovery parser extracts robots, sitemaps, hreflangs, and schemas',
    level: 'E2',
    sourceType: 'AutomatedTest',
    result: 'PASS',
    actualResult: '4/4 discovery assertions passed in tests/public_discovery.test.ts',
  },
  {
    id: 'EVD-007',
    wpId: 'WP-01',
    claim: 'Discovered observations carry provenance, timestamps, and DJB2 hash checksums',
    level: 'E2',
    sourceType: 'AutomatedTest',
    result: 'PASS',
    actualResult: 'Observation contract verified with valid checksum and confidence metadata',
  },
  {
    id: 'EVD-008',
    wpId: 'WP-01',
    claim: 'All bootstrap & discovery tests pass with exit code 0',
    level: 'E2',
    sourceType: 'AutomatedTest',
    result: 'PASS',
    actualResult: '11/11 tests green (tests/runner.ts exit code 0)',
  },
  {
    id: 'EVD-009',
    wpId: 'WP-01',
    claim: 'Zero remote production mutations and zero cloud deployments performed',
    level: 'E2',
    sourceType: 'LocalExecution',
    result: 'PASS',
    actualResult: 'Remote writes = 0, Cloud Run deployments = 0',
  },
  {
    id: 'EVD-010',
    wpId: 'WP-01',
    claim: 'Controller Report Schema 1.0 emitted completely per Section 26 contract',
    level: 'E1',
    sourceType: 'ControllerReport',
    result: 'PASS',
    actualResult: 'Emitted with complete provenance at execution cycle conclusion',
  },
];
